"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import { rupiah } from "@/lib/ui";
import { Pencil, Plus, Power, Sparkles, X } from "lucide-react";

type Service={id:string;name:string;category:string|null;pricing_mode:string;unit_label:string;base_price:number;min_quantity:number;estimated_minutes:number|null;description:string|null;is_active:boolean};
const init={name:"",category:"Kiloan",pricing_mode:"weight",unit_label:"kg",base_price:"",min_quantity:"0",estimated_minutes:"1440",description:""};
export default function ServicesPage(){const supabase=createClient();const[rows,setRows]=useState<Service[]>([]),[tenantId,setTenantId]=useState(""),[form,setForm]=useState(init),[editing,setEditing]=useState<Service|null>(null),[msg,setMsg]=useState("");
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:m}=await supabase.from("tenant_memberships").select("tenant_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!m)return;setTenantId(m.tenant_id);const{data}=await supabase.from("services").select("id,name,category,pricing_mode,unit_label,base_price,min_quantity,estimated_minutes,description,is_active").eq("tenant_id",m.tenant_id).is("deleted_at",null).order("name");setRows((data??[]) as Service[])}useEffect(()=>{load()},[]);
async function save(e:FormEvent){e.preventDefault();setMsg("");const payload={name:form.name,category:form.category||null,pricing_mode:form.pricing_mode,unit_label:form.unit_label,base_price:Number(form.base_price||0),min_quantity:Number(form.min_quantity||0),estimated_minutes:form.estimated_minutes?Number(form.estimated_minutes):null,description:form.description||null};const res=editing?await supabase.from("services").update(payload).eq("id",editing.id):await supabase.from("services").insert({tenant_id:tenantId,...payload});if(res.error)return setMsg(res.error.message);setForm(init);setEditing(null);setMsg("Tersimpan.");load()}
function edit(r:Service){setEditing(r);setForm({name:r.name,category:r.category||"",pricing_mode:r.pricing_mode,unit_label:r.unit_label,base_price:String(r.base_price),min_quantity:String(r.min_quantity||0),estimated_minutes:String(r.estimated_minutes||""),description:r.description||""});window.scrollTo({top:0,behavior:"smooth"})}
async function toggle(r:Service){await supabase.from("services").update({is_active:!r.is_active}).eq("id",r.id);load()}
return <div className="space-y-6"><div><h1 className="page-title">Layanan Laundry</h1><p className="muted mt-1">Kelola kiloan, satuan, paket, dan layanan flat.</p></div><div className="grid gap-5 xl:grid-cols-[390px_1fr]"><form onSubmit={save} className="card h-fit p-5"><div className="flex justify-between"><h2 className="section-title">{editing?"Edit Layanan":"Tambah Layanan"}</h2>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(init)}}><X size={18}/></button>}</div><div className="mt-4 space-y-3"><input className="input" placeholder="Nama layanan" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input className="input" placeholder="Kategori: Kiloan / Satuan / Express" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/><div className="grid grid-cols-2 gap-3"><select className="input" value={form.pricing_mode} onChange={e=>{const v=e.target.value;setForm({...form,pricing_mode:v,unit_label:v==="weight"?"kg":v==="unit"?"pcs":"paket"})}}><option value="weight">Per Berat</option><option value="unit">Per Unit</option><option value="package">Paket</option><option value="flat">Flat</option></select><input className="input" placeholder="Satuan" value={form.unit_label} onChange={e=>setForm({...form,unit_label:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><input className="input" type="number" min="0" placeholder="Harga" value={form.base_price} onChange={e=>setForm({...form,base_price:e.target.value})} required/><input className="input" type="number" step="0.1" min="0" placeholder="Minimal qty" value={form.min_quantity} onChange={e=>setForm({...form,min_quantity:e.target.value})}/></div><input className="input" type="number" min="0" placeholder="Estimasi menit (1440 = 1 hari)" value={form.estimated_minutes} onChange={e=>setForm({...form,estimated_minutes:e.target.value})}/><textarea className="input min-h-20" placeholder="Deskripsi" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>{msg&&<div className="rounded-xl bg-sky-50 p-3 text-sm text-sky-700">{msg}</div>}<button className="btn-primary w-full gap-2">{editing?<Pencil size={16}/>:<Plus size={16}/>} {editing?"Update":"Simpan"}</button></div></form>
<div className="grid gap-3 sm:grid-cols-2 2xl:grid-cols-3">{rows.map(r=><div key={r.id} className={`card p-5 ${!r.is_active?"opacity-60":""}`}><div className="flex items-start justify-between gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-violet-100 to-sky-100 text-violet-700"><Sparkles size={18}/></div><span className={r.is_active?"badge-success":"badge-neutral"}>{r.is_active?"Aktif":"Off"}</span></div><div className="mt-4 font-black">{r.name}</div><div className="mt-1 text-xs text-slate-500">{r.category||"Tanpa kategori"} • {r.pricing_mode} / {r.unit_label}</div><div className="mt-3 text-2xl font-black">{rupiah(r.base_price)}</div><div className="mt-4 flex gap-2"><button onClick={()=>edit(r)} className="btn-secondary flex-1 gap-1 px-3 py-2 text-sm"><Pencil size={14}/> Edit</button><button onClick={()=>toggle(r)} className="btn-secondary px-3 py-2"><Power size={15}/></button></div></div>)}</div></div></div>}
