"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import { rupiah } from "@/lib/ui";
import { Clock3, Coins, Layers3, Pencil, Plus, Power, Scale, Sparkles, X } from "lucide-react";

type Service={id:string;name:string;category:string|null;pricing_mode:string;unit_label:string;base_price:number;min_quantity:number;estimated_minutes:number|null;description:string|null;is_active:boolean};
const init={name:"",category:"Kiloan",pricing_mode:"weight",unit_label:"kg",base_price:"",min_quantity:"0",estimated_minutes:"1440",description:""};
export default function ServicesPage(){const supabase=createClient();const[rows,setRows]=useState<Service[]>([]),[tenantId,setTenantId]=useState(""),[form,setForm]=useState(init),[editing,setEditing]=useState<Service|null>(null),[msg,setMsg]=useState("");
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:m}=await supabase.from("tenant_memberships").select("tenant_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!m)return;setTenantId(m.tenant_id);const{data}=await supabase.from("services").select("id,name,category,pricing_mode,unit_label,base_price,min_quantity,estimated_minutes,description,is_active").eq("tenant_id",m.tenant_id).is("deleted_at",null).order("name");setRows((data??[]) as Service[])}useEffect(()=>{load()},[]);
async function save(e:FormEvent){e.preventDefault();setMsg("");const payload={name:form.name,category:form.category||null,pricing_mode:form.pricing_mode,unit_label:form.unit_label,base_price:Number(form.base_price||0),min_quantity:Number(form.min_quantity||0),estimated_minutes:form.estimated_minutes?Number(form.estimated_minutes):null,description:form.description||null};const res=editing?await supabase.from("services").update(payload).eq("id",editing.id):await supabase.from("services").insert({tenant_id:tenantId,...payload});if(res.error)return setMsg(res.error.message);setForm(init);setEditing(null);setMsg("Tersimpan.");load()}
function edit(r:Service){setEditing(r);setForm({name:r.name,category:r.category||"",pricing_mode:r.pricing_mode,unit_label:r.unit_label,base_price:String(r.base_price),min_quantity:String(r.min_quantity||0),estimated_minutes:String(r.estimated_minutes||""),description:r.description||""});window.scrollTo({top:0,behavior:"smooth"})}
async function toggle(r:Service){await supabase.from("services").update({is_active:!r.is_active}).eq("id",r.id);load()}
function duration(minutes:number|null){if(!minutes)return "Tanpa estimasi";if(minutes%1440===0)return `${minutes/1440} hari`;if(minutes>=60)return `${Math.round(minutes/60)} jam`;return `${minutes} menit`}
return <div className="space-y-6">
 <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="content-kicker"><Sparkles size={14}/> SERVICE CATALOG</div><h1 className="page-title mt-2">Layanan Laundry</h1><p className="muted mt-1">Kelola kiloan, satuan, paket, harga dasar, dan estimasi pengerjaan.</p></div><div className="theme-card theme-card-6 px-4 py-3"><div className="text-xs font-bold text-slate-500">Layanan aktif</div><div className="text-xl font-black">{rows.filter(r=>r.is_active).length}</div></div></div>
 <div className="grid gap-5 xl:grid-cols-[420px_1fr]">
  <form onSubmit={save} className="premium-panel h-fit p-5 xl:sticky xl:top-24">
   <div className="premium-form-head flex items-center justify-between"><div className="flex items-center gap-3"><div className="brand-gradient grid h-10 w-10 place-items-center rounded-2xl text-white shadow"><Sparkles size={19}/></div><div><h2 className="section-title">{editing?"Edit Layanan":"Tambah Layanan"}</h2><p className="text-xs text-slate-500">Harga dasar dapat dioverride per cabang nanti.</p></div></div>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(init)}} className="rounded-xl bg-white/70 p-2"><X size={18}/></button>}</div>
   <div className="space-y-3">
    <div><label className="label">Nama Layanan</label><input className="input" placeholder="Contoh: Cuci Setrika Express" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div>
    <div><label className="label">Kategori</label><input className="input" placeholder="Kiloan / Satuan / Express / Bedding" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></div>
    <div className="grid grid-cols-2 gap-3"><div><label className="label">Model Harga</label><select className="input" value={form.pricing_mode} onChange={e=>{const v=e.target.value;setForm({...form,pricing_mode:v,unit_label:v==="weight"?"kg":v==="unit"?"pcs":"paket"})}}><option value="weight">Per Berat</option><option value="unit">Per Unit</option><option value="package">Paket</option><option value="flat">Flat</option></select></div><div><label className="label">Satuan</label><input className="input" placeholder="kg / pcs / paket" value={form.unit_label} onChange={e=>setForm({...form,unit_label:e.target.value})}/></div></div>
    <div className="grid grid-cols-2 gap-3"><div><label className="label">Harga Dasar</label><div className="relative"><Coins className="absolute left-3 top-3 text-slate-400" size={16}/><input className="input pl-9" type="number" min="0" placeholder="0" value={form.base_price} onChange={e=>setForm({...form,base_price:e.target.value})} required/></div></div><div><label className="label">Minimum Qty</label><div className="relative"><Scale className="absolute left-3 top-3 text-slate-400" size={16}/><input className="input pl-9" type="number" step="0.1" min="0" placeholder="0" value={form.min_quantity} onChange={e=>setForm({...form,min_quantity:e.target.value})}/></div></div></div>
    <div><label className="label">Estimasi Pengerjaan</label><div className="relative"><Clock3 className="absolute left-3 top-3 text-slate-400" size={16}/><input className="input pl-9" type="number" min="0" placeholder="1440 = 1 hari" value={form.estimated_minutes} onChange={e=>setForm({...form,estimated_minutes:e.target.value})}/></div><div className="mt-1 text-xs text-slate-400">Contoh 720 = 12 jam, 1440 = 1 hari.</div></div>
    <div><label className="label">Deskripsi</label><textarea className="input min-h-20" placeholder="Detail layanan untuk kasir/homepage" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div>
    {msg&&<div className="rounded-xl bg-sky-50/80 p-3 text-sm text-sky-700 ring-1 ring-sky-100">{msg}</div>}
    <button className="btn-primary w-full gap-2">{editing?<Pencil size={16}/>:<Plus size={16}/>} {editing?"Update Layanan":"Simpan Layanan"}</button>
   </div>
  </form>
  <section className="premium-panel p-4"><div className="mb-4 flex items-center justify-between"><div><div className="font-black text-slate-900">Katalog Layanan</div><div className="text-xs text-slate-500">Setiap card otomatis mengikuti warna tema.</div></div><div className="grid h-10 w-10 place-items-center rounded-2xl bg-white/60 text-[var(--brand-primary)] shadow-sm"><Layers3 size={18}/></div></div>
   <div className="grid gap-4 sm:grid-cols-2 2xl:grid-cols-3">{rows.map((r,i)=><div key={r.id} className={`theme-card theme-card-${(i%8)+1} relative overflow-hidden p-5 ${!r.is_active?"opacity-60 grayscale-[.2]":""}`}><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full bg-white/35 blur-xl"/><div className="relative"><div className="flex items-start justify-between gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/65 text-[var(--brand-primary)] shadow-sm"><Sparkles size={18}/></div><span className={r.is_active?"badge-success":"badge-neutral"}>{r.is_active?"Aktif":"Off"}</span></div><div className="mt-4 text-lg font-black">{r.name}</div><div className="mt-1 text-xs font-medium text-slate-500">{r.category||"Tanpa kategori"} • {r.pricing_mode} / {r.unit_label}</div><div className="mt-4 text-2xl font-black tracking-tight">{rupiah(r.base_price)}<span className="ml-1 text-xs font-semibold text-slate-500">/{r.unit_label}</span></div><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/55 p-2.5"><div className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Minimum</div><div className="mt-0.5 text-sm font-black">{r.min_quantity||0} {r.unit_label}</div></div><div className="rounded-xl bg-white/55 p-2.5"><div className="text-[10px] font-bold uppercase tracking-wide text-slate-400">Estimasi</div><div className="mt-0.5 text-sm font-black">{duration(r.estimated_minutes)}</div></div></div>{r.description&&<p className="mt-3 line-clamp-2 text-xs leading-5 text-slate-500">{r.description}</p>}<div className="mt-4 flex gap-2"><button onClick={()=>edit(r)} className="btn-secondary flex-1 gap-1 !px-3 !py-2 text-sm"><Pencil size={14}/> Edit</button><button onClick={()=>toggle(r)} className="btn-secondary !px-3 !py-2" title="Aktif/nonaktif"><Power size={15}/></button></div></div></div>)}
   {!rows.length&&<div className="premium-empty sm:col-span-2 2xl:col-span-3"><div className="text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-white/70 text-[var(--brand-primary)] shadow-sm"><Sparkles size={24}/></div><div className="mt-3 font-bold text-slate-600">Belum ada layanan</div><div className="mt-1 text-xs">Buat layanan pertama dari form di sebelah kiri.</div></div></div>}</div>
  </section>
 </div>
</div>}
