"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import { Building2, MapPin, Pencil, Plus, Power, X } from "lucide-react";
type Branch={id:string;name:string;code:string|null;phone:string|null;email:string|null;address:string|null;city:string|null;province:string|null;is_main:boolean;is_active:boolean};
const init={name:"",code:"",phone:"",email:"",address:"",city:"",province:""};
export default function BranchesPage(){const supabase=createClient();const[rows,setRows]=useState<Branch[]>([]),[tenantId,setTenantId]=useState(""),[form,setForm]=useState(init),[editing,setEditing]=useState<Branch|null>(null),[msg,setMsg]=useState("");
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:m}=await supabase.from("tenant_memberships").select("tenant_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!m)return;setTenantId(m.tenant_id);const{data}=await supabase.from("branches").select("id,name,code,phone,email,address,city,province,is_main,is_active").eq("tenant_id",m.tenant_id).order("is_main",{ascending:false}).order("name");setRows((data??[]) as Branch[])}useEffect(()=>{load()},[]);
async function save(e:FormEvent){e.preventDefault();setMsg("");const payload={name:form.name,code:form.code||null,phone:form.phone||null,email:form.email||null,address:form.address||null,city:form.city||null,province:form.province||null};const res=editing?await supabase.from("branches").update(payload).eq("id",editing.id):await supabase.from("branches").insert({tenant_id:tenantId,...payload});if(res.error)return setMsg(res.error.message);setForm(init);setEditing(null);setMsg("Tersimpan.");load()}
function edit(r:Branch){setEditing(r);setForm({name:r.name,code:r.code||"",phone:r.phone||"",email:r.email||"",address:r.address||"",city:r.city||"",province:r.province||""});window.scrollTo({top:0,behavior:"smooth"})}
async function toggle(r:Branch){if(r.is_main&&r.is_active)return setMsg("Cabang utama jangan dinonaktifkan.");await supabase.from("branches").update({is_active:!r.is_active}).eq("id",r.id);load()}
return <div className="space-y-6"><div><h1 className="page-title">Cabang</h1><p className="muted mt-1">Satu bisnis, banyak outlet, satu dashboard.</p></div><div className="grid gap-5 xl:grid-cols-[390px_1fr]"><form onSubmit={save} className="card h-fit p-5"><div className="flex justify-between"><h2 className="section-title">{editing?"Edit Cabang":"Tambah Cabang"}</h2>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(init)}}><X size={18}/></button>}</div><div className="mt-4 space-y-3"><div className="grid grid-cols-[1fr_120px] gap-3"><input className="input" placeholder="Nama cabang" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input className="input" placeholder="Kode" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><input className="input" placeholder="Nomor WA" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="input" type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><textarea className="input min-h-20" placeholder="Alamat" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/><div className="grid grid-cols-2 gap-3"><input className="input" placeholder="Kota" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/><input className="input" placeholder="Provinsi" value={form.province} onChange={e=>setForm({...form,province:e.target.value})}/></div>{msg&&<div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-700">{msg}</div>}<button className="btn-primary w-full gap-2">{editing?<Pencil size={16}/>:<Plus size={16}/>} {editing?"Update Cabang":"Tambah Cabang"}</button></div></form>
<div className="grid gap-4 sm:grid-cols-2">{rows.map(r=><div key={r.id} className={`card p-5 ${!r.is_active?"opacity-60":""}`}><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-600 to-sky-500 text-white"><Building2 size={20}/></div><div className="flex gap-2">{r.is_main&&<span className="badge-info">Utama</span>}<span className={r.is_active?"badge-success":"badge-neutral"}>{r.is_active?"Aktif":"Off"}</span></div></div><div className="mt-4 text-lg font-black">{r.name}</div><div className="text-sm text-slate-500">{r.code||"Tanpa kode"}</div>{(r.address||r.city)&&<div className="mt-3 flex gap-2 text-sm text-slate-500"><MapPin size={16}/><span>{[r.address,r.city,r.province].filter(Boolean).join(", ")}</span></div>}<div className="mt-4 flex gap-2"><button onClick={()=>edit(r)} className="btn-secondary flex-1 gap-1 px-3 py-2 text-sm"><Pencil size={14}/> Edit</button><button onClick={()=>toggle(r)} className="btn-secondary px-3 py-2"><Power size={15}/></button></div></div>)}</div></div></div>}
