"use client";
import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase-browser";
import { rupiah, statusClass, statusLabel, dateTime } from "@/lib/ui";
import { Banknote, Clock3, Printer, Shirt, UserRound } from "lucide-react";
const statuses=["received","washing","drying","ironing","ready","out_for_delivery","completed","cancelled"];
export default function OrderDetail(){const{id}=useParams<{id:string}>();const supabase=createClient();const[order,setOrder]=useState<any>(null),[items,setItems]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[history,setHistory]=useState<any[]>([]),[amount,setAmount]=useState(""),[method,setMethod]=useState("cash"),[ref,setRef]=useState(""),[msg,setMsg]=useState("");
async function load(){const{data:o}=await supabase.from("orders").select("*,branches(name,address,phone)").eq("id",id).single();setOrder(o);const[{data:i},{data:p},{data:h}]=await Promise.all([supabase.from("order_items").select("*").eq("order_id",id).is("deleted_at",null).order("created_at"),supabase.from("payments").select("*").eq("order_id",id).is("deleted_at",null).order("created_at",{ascending:false}),supabase.from("order_status_history").select("*").eq("order_id",id).order("created_at",{ascending:false})]);setItems(i??[]);setPayments(p??[]);setHistory(h??[])}useEffect(()=>{load()},[id]);
async function setStatus(v:string){setMsg("");const{error}=await supabase.rpc("update_order_status",{p_order_id:id,p_status:v});if(error)setMsg(error.message);load()}
async function pay(e:FormEvent){e.preventDefault();if(!order)return;setMsg("");const{error}=await supabase.from("payments").insert({tenant_id:order.tenant_id,branch_id:order.branch_id,order_id:id,amount:Number(amount),payment_method:method,status:"verified",transaction_ref:ref||null,verified_at:new Date().toISOString()});if(error)return setMsg(error.message);setAmount("");setRef("");load()}
if(!order)return <div className="muted">Loading...</div>;
return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h1 className="page-title">{order.order_number}</h1><span className={statusClass(order.status)}>{statusLabel[order.status]||order.status}</span></div><p className="muted mt-1">{order.customer_name} • {order.branches?.name}</p></div><button onClick={()=>window.print()} className="btn-secondary gap-2"><Printer size={16}/> Print</button></div>{msg&&<div className="rounded-xl bg-rose-50 p-3 text-sm text-rose-600">{msg}</div>}
<div className="grid gap-5 xl:grid-cols-[1fr_360px]"><div className="space-y-5"><div className="card p-5"><div className="flex items-center gap-2"><Shirt className="text-violet-600"/><h2 className="section-title">Proses Cucian</h2></div><div className="mt-4 flex flex-wrap gap-2">{statuses.map(s=><button key={s} onClick={()=>setStatus(s)} className={`rounded-full px-3 py-2 text-xs font-bold transition ${order.status===s?"bg-gradient-to-r from-violet-600 to-sky-500 text-white shadow":"bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{statusLabel[s]||s}</button>)}</div></div>
<div className="card overflow-hidden"><div className="border-b border-slate-100 p-4 font-bold">Item Laundry</div>{items.map(i=><div key={i.id} className="flex justify-between gap-3 border-b border-slate-100 p-4 text-sm"><div><div className="font-bold">{i.item_name}</div><div className="text-slate-500">{i.quantity} {i.unit_label} × {rupiah(i.unit_price)}</div>{i.notes&&<div className="mt-1 text-xs text-slate-400">{i.notes}</div>}</div><div className="font-black">{rupiah(i.line_total)}</div></div>)}</div>
<div className="card p-5"><div className="flex items-center gap-2"><Clock3 className="text-sky-600"/><h2 className="section-title">Riwayat Status</h2></div><div className="mt-4 space-y-3">{history.map(h=><div key={h.id} className="flex gap-3"><div className="mt-1 h-2.5 w-2.5 rounded-full bg-violet-500"/><div><div className="text-sm font-bold">{statusLabel[h.to_status]||h.to_status}</div><div className="text-xs text-slate-400">{dateTime(h.created_at)}</div></div></div>)}</div></div></div>
<div className="space-y-5"><div className="card-violet p-5"><div className="text-xs font-bold uppercase tracking-wider text-violet-500">Grand Total</div><div className="mt-1 text-3xl font-black">{rupiah(order.grand_total)}</div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-emerald-50 p-3"><span className="text-emerald-600">Dibayar</span><br/><b>{rupiah(order.paid_amount)}</b></div><div className="rounded-xl bg-amber-50 p-3"><span className="text-amber-600">Sisa</span><br/><b>{rupiah(order.balance_due)}</b></div></div></div>
<div className="card p-5"><div className="flex items-center gap-2"><UserRound className="text-violet-600"/><h2 className="section-title">Pelanggan</h2></div><div className="mt-3 font-bold">{order.customer_name}</div><div className="text-sm text-slate-500">{order.customer_phone||"Tanpa WA"}</div><div className="mt-3 text-xs text-slate-400">Masuk: {dateTime(order.received_at)}<br/>Estimasi: {dateTime(order.promised_at)}</div></div>
<form onSubmit={pay} className="card p-5"><div className="flex items-center gap-2"><Banknote className="text-emerald-600"/><h2 className="section-title">Pembayaran</h2></div><div className="mt-4 space-y-3"><input className="input" type="number" min="1" max={Math.max(Number(order.balance_due||0),1)} placeholder="Nominal" value={amount} onChange={e=>setAmount(e.target.value)} required/><select className="input" value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="bank_transfer">Transfer</option><option value="qris">QRIS</option><option value="ewallet">E-Wallet</option><option value="other">Lainnya</option></select><input className="input" placeholder="Ref transaksi (opsional)" value={ref} onChange={e=>setRef(e.target.value)}/><button className="btn-primary w-full">Catat Pembayaran</button></div></form>
<div className="card p-5"><h2 className="section-title">Riwayat Bayar</h2><div className="mt-3 space-y-2">{payments.map(p=><div key={p.id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{rupiah(p.amount)}</b><div className="text-xs text-slate-500">{p.payment_method} • {p.status} • {dateTime(p.created_at)}</div></div>)}{!payments.length&&<div className="text-sm text-slate-400">Belum ada pembayaran.</div>}</div></div></div></div></div>}
