"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import { Bell, KeyRound, Mail, MessageCircle, Save, Send, ShieldCheck } from "lucide-react";

type Channel={channel:string;provider:string;is_enabled:boolean;credentials_configured:boolean;public_config:any;last_test_status:string|null;last_test_message:string|null};
const providerOptions:any={whatsapp:["fonnte","starsender"],email:["mailketing","smtp","gmail"],telegram:["telegram"]};
const icons:any={whatsapp:MessageCircle,email:Mail,telegram:Send};

export default function NotificationsPage(){
 const supabase=createClient();const[tenantId,setTenantId]=useState("");const[rows,setRows]=useState<Channel[]>([]);const[selected,setSelected]=useState("whatsapp");const[provider,setProvider]=useState("fonnte");const[enabled,setEnabled]=useState(false);const[config,setConfig]=useState<any>({});const[secret,setSecret]=useState("");const[msg,setMsg]=useState("");const[templates,setTemplates]=useState<any[]>([]);const[authSettings,setAuthSettings]=useState<any>({require_login_otp:false,allow_whatsapp:true,allow_email:true,allow_telegram:true,otp_expiry_minutes:5,resend_cooldown_seconds:60,max_attempts:5});
 async function load(){const{data:{session}}=await supabase.auth.getSession();const user=session?.user;if(!user)return;const{data:m}=await supabase.from("tenant_memberships").select("tenant_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!m)return;setTenantId(m.tenant_id);const[{data:c},{data:t},{data:a}]=await Promise.all([supabase.from("notification_channels").select("channel,provider,is_enabled,credentials_configured,public_config,last_test_status,last_test_message").eq("tenant_id",m.tenant_id).order("channel"),supabase.from("notification_templates").select("id,event_key,channel,subject,body,is_active").eq("tenant_id",m.tenant_id).order("event_key"),supabase.from("tenant_auth_settings").select("require_login_otp,allow_whatsapp,allow_email,allow_telegram,otp_expiry_minutes,resend_cooldown_seconds,max_attempts").eq("tenant_id",m.tenant_id).maybeSingle()]);setRows((c??[]) as Channel[]);setTemplates(t??[]);if(a)setAuthSettings(a);const cur=(c??[]).find((x:any)=>x.channel===selected)||(c??[])[0];if(cur)apply(cur)}
 function apply(c:any){setSelected(c.channel);setProvider(c.provider);setEnabled(c.is_enabled);setConfig(c.public_config||{});setSecret("");setMsg("")}
 useEffect(()=>{load()},[]);
 async function saveChannel(e:FormEvent){e.preventDefault();setMsg("");const{error}=await supabase.rpc("update_notification_channel",{p_tenant_id:tenantId,p_channel:selected,p_enabled:enabled,p_provider:provider,p_public_config:config});if(error)return setMsg(error.message);if(secret.trim()){const credentials=provider==="smtp"?{password:secret}:provider==="gmail"?{app_password:secret}:provider==="telegram"?{bot_token:secret}:{api_token:secret};const{error:se}=await supabase.rpc("save_notification_credentials",{p_tenant_id:tenantId,p_channel:selected,p_credentials:credentials});if(se)return setMsg(se.message)}setMsg("Pengaturan notifikasi tersimpan.");load()}
 async function saveAuthSettings(){setMsg("");const{error}=await supabase.from("tenant_auth_settings").update(authSettings).eq("tenant_id",tenantId);setMsg(error?error.message:"Pengaturan OTP login tersimpan.")}
 async function updateTemplate(row:any,field:string,value:any){setTemplates(v=>v.map(x=>x.id===row.id?{...x,[field]:value}:x))}
 async function saveTemplates(){setMsg("");for(const t of templates){const{error}=await supabase.from("notification_templates").update({subject:t.subject||null,body:t.body,is_active:t.is_active}).eq("id",t.id);if(error)return setMsg(error.message)}setMsg("Template tersimpan.")}
 const current=rows.find(r=>r.channel===selected); const Icon=icons[selected]||Bell;
 return <div className="space-y-6"><div><h1 className="page-title">Notifikasi & Gateway</h1><p className="muted mt-1">BYOK per tenant: Fonnte, StarSender, Mailketing, SMTP/Gmail, dan Telegram.</p></div>
 <div className="card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-600 to-sky-500 text-white"><KeyRound size={20}/></div><div><h2 className="section-title">OTP Login Multi-Channel</h2><p className="muted">User memilih WhatsApp, Email, atau Telegram yang benar-benar tersedia.</p></div></div><label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3"><input type="checkbox" checked={!!authSettings.require_login_otp} onChange={e=>setAuthSettings({...authSettings,require_login_otp:e.target.checked})}/><span className="font-semibold">Wajibkan OTP saat login</span></label></div><div className="mt-5 grid gap-3 md:grid-cols-3">{["whatsapp","email","telegram"].map(ch=>{const row=rows.find(r=>r.channel===ch);const connected=!!row?.is_enabled&&!!row?.credentials_configured;const key=`allow_${ch}`;return <label key={ch} className={`rounded-2xl border p-4 ${connected?"border-emerald-200 bg-emerald-50/60":"border-slate-200 bg-slate-50"}`}><div className="flex items-center justify-between gap-2"><span className="font-black capitalize">{ch}</span><span className={connected?"badge-success":"badge-neutral"}>{connected?"Connected":"Belum aktif"}</span></div><div className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={!!authSettings[key]} onChange={e=>setAuthSettings({...authSettings,[key]:e.target.checked})}/><span>Izinkan untuk OTP</span></div></label>})}</div><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><label className="label">OTP berlaku (menit)</label><input className="input" type="number" min={1} max={15} value={authSettings.otp_expiry_minutes||5} onChange={e=>setAuthSettings({...authSettings,otp_expiry_minutes:Number(e.target.value)})}/></div><div><label className="label">Resend cooldown (detik)</label><input className="input" type="number" min={30} max={300} value={authSettings.resend_cooldown_seconds||60} onChange={e=>setAuthSettings({...authSettings,resend_cooldown_seconds:Number(e.target.value)})}/></div><div><label className="label">Maks. percobaan</label><input className="input" type="number" min={3} max={10} value={authSettings.max_attempts||5} onChange={e=>setAuthSettings({...authSettings,max_attempts:Number(e.target.value)})}/></div></div><button onClick={saveAuthSettings} className="btn-primary mt-5 gap-2" type="button"><Save size={16}/> Simpan OTP Login</button></div>
 <div className="grid gap-4 md:grid-cols-3">{rows.map(r=>{const I=icons[r.channel]||Bell;return <button key={r.channel} onClick={()=>apply(r)} className={`card p-5 text-left transition ${selected===r.channel?"ring-2 ring-violet-400":"hover:-translate-y-0.5"}`}><div className="flex items-center justify-between"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-100 to-sky-100 text-violet-700"><I size={20}/></div><span className={r.is_enabled?"badge-success":"badge-neutral"}>{r.is_enabled?"Aktif":"Off"}</span></div><div className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-400">{r.channel}</div><div className="mt-1 text-xl font-black capitalize">{r.provider}</div><div className="mt-2 text-xs text-slate-500">Credential: {r.credentials_configured?"Tersimpan":"Belum diisi"}</div></button>})}</div>
 <form onSubmit={saveChannel} className="card p-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-600 to-sky-500 text-white"><Icon size={20}/></div><div><h2 className="section-title capitalize">Setting {selected}</h2><p className="muted">Credential rahasia tidak pernah ditampilkan kembali.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><label className="label">Provider</label><select className="input" value={provider} onChange={e=>{setProvider(e.target.value);setSecret("")}}>{providerOptions[selected]?.map((p:string)=><option key={p} value={p}>{p}</option>)}</select></div><label className="flex items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)} className="h-4 w-4"/><span className="font-semibold">Aktifkan channel ini</span></label>
 {selected==="email"&&provider==="mailketing"&&<><div><label className="label">From Name</label><input className="input" value={config.from_name||""} onChange={e=>setConfig({...config,from_name:e.target.value})}/></div><div><label className="label">From Email</label><input className="input" type="email" value={config.from_email||""} onChange={e=>setConfig({...config,from_email:e.target.value})}/></div></>}
 {selected==="email"&&provider==="smtp"&&<><div><label className="label">SMTP Host</label><input className="input" value={config.smtp_host||""} onChange={e=>setConfig({...config,smtp_host:e.target.value})}/></div><div><label className="label">Port</label><input className="input" value={config.smtp_port||465} onChange={e=>setConfig({...config,smtp_port:Number(e.target.value)})}/></div><div><label className="label">Username</label><input className="input" value={config.smtp_username||""} onChange={e=>setConfig({...config,smtp_username:e.target.value})}/></div><div><label className="label">Secure</label><select className="input" value={config.smtp_secure||"ssl"} onChange={e=>setConfig({...config,smtp_secure:e.target.value})}><option value="ssl">SSL</option><option value="tls">TLS</option><option value="none">None</option></select></div><div><label className="label">From Name</label><input className="input" value={config.from_name||""} onChange={e=>setConfig({...config,from_name:e.target.value})}/></div><div><label className="label">From Email</label><input className="input" value={config.from_email||""} onChange={e=>setConfig({...config,from_email:e.target.value})}/></div></>}
 {selected==="email"&&provider==="gmail"&&<><div><label className="label">Alamat Gmail</label><input className="input" type="email" value={config.gmail_address||""} onChange={e=>setConfig({...config,gmail_address:e.target.value,from_email:e.target.value})}/></div><div><label className="label">From Name</label><input className="input" value={config.from_name||""} onChange={e=>setConfig({...config,from_name:e.target.value})}/></div></>}
 {selected==="telegram"&&<div><label className="label">Bot Username</label><input className="input" placeholder="@botanda" value={config.bot_username||""} onChange={e=>setConfig({...config,bot_username:e.target.value})}/></div>}
 <div className="md:col-span-2"><label className="label">{provider==="smtp"?"SMTP Password":provider==="gmail"?"Google App Password":provider==="telegram"?"Bot Token":"API Token"}</label><input className="input" type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder={current?.credentials_configured?"Kosongkan jika tidak ingin mengganti credential":"Isi credential provider"}/><div className="mt-1 flex items-center gap-1 text-xs text-slate-400"><ShieldCheck size={13}/> Disimpan di schema private, bukan tabel public.</div></div></div>{msg&&<div className="mt-4 rounded-xl bg-sky-50 p-3 text-sm text-sky-700">{msg}</div>}<button className="btn-primary mt-5 gap-2"><Save size={16}/> Simpan Gateway</button></form>
 <div className="card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="section-title">Template Notifikasi</h2><p className="muted">Edit pesan otomatis per event dan channel.</p></div><button onClick={saveTemplates} className="btn-primary gap-2"><Save size={16}/> Simpan Template</button></div><div className="space-y-4 p-5">{templates.map(t=><div key={t.id} className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><div className="mb-3 flex flex-wrap items-center gap-2"><span className="badge-info">{t.event_key}</span><span className="badge-neutral">{t.channel}</span><label className="ml-auto flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={t.is_active} onChange={e=>updateTemplate(t,"is_active",e.target.checked)}/> Aktif</label></div>{t.channel==="email"&&<input className="input mb-2" value={t.subject||""} onChange={e=>updateTemplate(t,"subject",e.target.value)} placeholder="Subject"/>}<textarea className="input min-h-24" value={t.body} onChange={e=>updateTemplate(t,"body",e.target.value)}/></div>)}</div></div></div>
}
