"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import { Pencil, Plus, Search, UserRound, UserX, X } from "lucide-react";

type Customer={id:string;full_name:string;phone:string|null;email:string|null;address:string|null;notes:string|null;status:string;telegram_chat_id?:string|null;notify_whatsapp?:boolean;notify_email?:boolean;notify_telegram?:boolean};
const empty={full_name:"",phone:"",email:"",address:"",notes:""};

export default function CustomersPage(){
 const supabase=createClient(); const[rows,setRows]=useState<Customer[]>([]); const[tenantId,setTenantId]=useState(""); const[form,setForm]=useState(empty); const[editing,setEditing]=useState<Customer|null>(null); const[search,setSearch]=useState(""); const[msg,setMsg]=useState("");
 async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:m}=await supabase.from("tenant_memberships").select("tenant_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!m)return;setTenantId(m.tenant_id);let q=supabase.from("customers").select("id,full_name,phone,email,address,notes,status,telegram_chat_id,notify_whatsapp,notify_email,notify_telegram").eq("tenant_id",m.tenant_id).is("deleted_at",null).order("created_at",{ascending:false}).limit(100);if(search.trim())q=q.or(`full_name.ilike.%${search.trim()}%,phone.ilike.%${search.trim()}%,email.ilike.%${search.trim()}%`);const{data}=await q;setRows((data??[]) as Customer[])}
 useEffect(()=>{load()},[]);
 async function save(e:FormEvent){e.preventDefault();setMsg("");if(editing){const{error}=await supabase.from("customers").update({...form}).eq("id",editing.id);if(error)return setMsg(error.message)}else{const{error}=await supabase.from("customers").insert({tenant_id:tenantId,...form});if(error)return setMsg(error.message)}setForm(empty);setEditing(null);setMsg("Tersimpan.");load()}
 function edit(r:Customer){setEditing(r);setForm({full_name:r.full_name,phone:r.phone||"",email:r.email||"",address:r.address||"",notes:r.notes||""});window.scrollTo({top:0,behavior:"smooth"})}
 async function toggle(r:Customer){await supabase.from("customers").update({status:r.status==="active"?"inactive":"active"}).eq("id",r.id);load()}
 return <div className="space-y-6"><div className="flex items-end justify-between gap-3"><div><h1 className="page-title">Pelanggan</h1><p className="muted mt-1">CRM sederhana untuk pelanggan semua cabang.</p></div><span className="badge-info">{rows.length} data</span></div>
 <div className="grid gap-5 xl:grid-cols-[380px_1fr]"><form onSubmit={save} className="card h-fit p-5"><div className="flex items-center justify-between"><h2 className="section-title">{editing?"Edit Pelanggan":"Tambah Pelanggan"}</h2>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}} className="rounded-lg p-1 hover:bg-slate-100"><X size={18}/></button>}</div><div className="mt-4 space-y-3"><div><label className="label">Nama</label><input className="input" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></div><div className="grid grid-cols-2 gap-3"><div><label className="label">WhatsApp</label><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><label className="label">Email</label><input className="input" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div></div><div><label className="label">Alamat</label><textarea className="input min-h-20" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div><div><label className="label">Catatan</label><textarea className="input min-h-20" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div>{msg&&<div className="rounded-xl bg-sky-50 p-3 text-sm text-sky-700">{msg}</div>}<button className="btn-primary w-full gap-2">{editing?<Pencil size={16}/>:<Plus size={16}/>} {editing?"Update":"Simpan"}</button></div></form>
 <div className="card overflow-hidden"><div className="border-b border-slate-100 p-4"><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={17}/><input className="input pl-9" placeholder="Cari nama, WA, email..." value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")load()}}/></div><button className="btn-secondary" onClick={load}>Cari</button></div></div><div className="divide-y divide-slate-100">{rows.map(r=><div key={r.id} className="flex items-center gap-3 p-4"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-100 to-sky-100 text-violet-700"><UserRound size={20}/></div><div className="min-w-0 flex-1"><div className="truncate font-bold">{r.full_name}</div><div className="truncate text-xs text-slate-500">{r.phone||"Tanpa WA"}{r.email?` • ${r.email}`:""}</div></div><span className={r.status==="active"?"badge-success":"badge-neutral"}>{r.status==="active"?"Aktif":"Nonaktif"}</span><button onClick={()=>edit(r)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Pencil size={17}/></button><button onClick={()=>toggle(r)} className="rounded-lg p-2 text-rose-500 hover:bg-rose-50"><UserX size={17}/></button></div>)}{!rows.length&&<div className="p-10 text-center text-sm text-slate-400">Belum ada pelanggan.</div>}</div></div></div></div>
}
