"use client";
import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase-browser";

export default function CustomersPage(){
 const supabase=createClient(); const [rows,setRows]=useState<any[]>([]); const [tenantId,setTenantId]=useState(""); const [name,setName]=useState(""); const [phone,setPhone]=useState(""); const [search,setSearch]=useState("");
 async function load(){ const {data:{user}}=await supabase.auth.getUser(); if(!user)return; const {data:m}=await supabase.from("tenant_memberships").select("tenant_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle(); if(!m)return; setTenantId(m.tenant_id); let q=supabase.from("customers").select("id,customer_code,full_name,phone,email,status,created_at").eq("tenant_id",m.tenant_id).is("deleted_at",null).order("created_at",{ascending:false}).limit(50); if(search.trim())q=q.ilike("full_name",`%${search.trim()}%`); const {data}=await q; setRows(data??[]); }
 useEffect(()=>{load();},[]);
 async function add(e:FormEvent){e.preventDefault(); if(!tenantId)return; await supabase.from("customers").insert({tenant_id:tenantId,full_name:name,phone}); setName("");setPhone("");load();}
 return <div className="space-y-6"><div><h1 className="page-title">Pelanggan</h1><p className="muted mt-1">Data pelanggan semua cabang.</p></div><div className="grid gap-5 xl:grid-cols-[360px_1fr]"><form onSubmit={add} className="card h-fit p-5"><h2 className="font-bold">Tambah Pelanggan</h2><div className="mt-4 space-y-3"><div><label className="label">Nama</label><input className="input" value={name} onChange={e=>setName(e.target.value)} required/></div><div><label className="label">WhatsApp</label><input className="input" value={phone} onChange={e=>setPhone(e.target.value)}/></div><button className="btn-primary w-full">Simpan</button></div></form><div className="card overflow-hidden"><div className="border-b p-4"><div className="flex gap-2"><input className="input" placeholder="Cari pelanggan..." value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn-secondary" onClick={load}>Cari</button></div></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-3">Nama</th><th className="p-3">WA</th><th className="p-3">Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3 font-semibold">{r.full_name}</td><td className="p-3">{r.phone||"-"}</td><td className="p-3 capitalize">{r.status}</td></tr>)}</tbody></table></div></div></div></div>
}
