"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase-browser";
import { rupiah, statusClass, statusLabel, dateTime } from "@/lib/ui";
import { Plus, Search, SlidersHorizontal } from "lucide-react";
const statuses=["all","received","washing","drying","ironing","ready","out_for_delivery","completed","cancelled"];
export default function OrdersPage(){const supabase=createClient();const[tenantId,setTenantId]=useState(""),[rows,setRows]=useState<any[]>([]),[branches,setBranches]=useState<any[]>([]),[branch,setBranch]=useState("all"),[status,setStatus]=useState("all"),[search,setSearch]=useState(""),[loading,setLoading]=useState(false);
async function init(){const{data:{session}}=await supabase.auth.getSession();const user=session?.user;if(!user)return;const{data:m}=await supabase.from("tenant_memberships").select("tenant_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!m)return;setTenantId(m.tenant_id);const{data:b}=await supabase.from("branches").select("id,name").eq("tenant_id",m.tenant_id).eq("is_active",true).order("is_main",{ascending:false});setBranches(b??[]);await load(m.tenant_id)}
async function load(tid=tenantId){if(!tid)return;setLoading(true);let q=supabase.from("orders").select("id,order_number,customer_name,customer_phone,status,payment_status,grand_total,balance_due,created_at,promised_at,branch_id,branches(name)").eq("tenant_id",tid).is("deleted_at",null).order("created_at",{ascending:false}).limit(100);if(branch!=="all")q=q.eq("branch_id",branch);if(status!=="all")q=q.eq("status",status);if(search.trim())q=q.or(`order_number.ilike.%${search.trim()}%,customer_name.ilike.%${search.trim()}%,customer_phone.ilike.%${search.trim()}%`);const{data}=await q;setRows(data??[]);setLoading(false)}
useEffect(()=>{init()},[]);useEffect(()=>{if(tenantId)load()},[branch,status]);const total=useMemo(()=>rows.reduce((s,r)=>s+Number(r.grand_total||0),0),[rows]);
return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="page-title">Order Laundry</h1><p className="muted mt-1">Cari dan pantau order semua cabang.</p></div><Link href="/orders/new" className="btn-primary gap-2"><Plus size={17}/> Order Baru</Link></div>
<div className="card p-4"><div className="grid gap-3 md:grid-cols-[1fr_180px_190px_auto]"><div className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input className="input pl-9" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()} placeholder="No order, nama atau WA..."/></div><select className="input" value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">Semua Cabang</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select className="input" value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s} value={s}>{s==="all"?"Semua Status":statusLabel[s]||s}</option>)}</select><button onClick={()=>load()} className="btn-secondary gap-2"><SlidersHorizontal size={16}/> {loading?"Memuat":"Terapkan"}</button></div></div>
<div className="flex flex-wrap gap-3"><span className="badge-neutral">{rows.length} order</span><span className="badge-info">Total {rupiah(total)}</span></div>
<div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Order</th><th className="p-4">Pelanggan</th><th className="p-4">Cabang</th><th className="p-4">Status</th><th className="p-4">Pembayaran</th><th className="p-4">Total</th><th className="p-4">Masuk</th><th className="p-4"></th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-slate-100 hover:bg-slate-50/70"><td className="p-4 font-black">{r.order_number}</td><td className="p-4"><div className="font-semibold">{r.customer_name}</div><div className="text-xs text-slate-400">{r.customer_phone||"-"}</div></td><td className="p-4">{r.branches?.name||"-"}</td><td className="p-4"><span className={statusClass(r.status)}>{statusLabel[r.status]||r.status}</span></td><td className="p-4"><span className={statusClass(r.payment_status)}>{statusLabel[r.payment_status]||r.payment_status}</span></td><td className="p-4 font-bold">{rupiah(r.grand_total)}</td><td className="p-4 text-xs text-slate-500">{dateTime(r.created_at)}</td><td className="p-4"><Link className="font-bold text-violet-600" href={`/orders/${r.id}`}>Detail</Link></td></tr>)}</tbody></table></div>{!rows.length&&<div className="p-12 text-center text-sm text-slate-400">Belum ada order yang cocok.</div>}</div></div>}
