"use client";

function esc(value: unknown) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export type ExportColumn<T> = { label: string; value: (row: T) => unknown };

export function exportExcelHtml<T>(filename: string, title: string, meta: string[], columns: ExportColumn<T>[], rows: T[]) {
  const head = columns.map((c) => `<th>${esc(c.label)}</th>`).join("");
  const body = rows.map((row) => `<tr>${columns.map((c) => `<td>${esc(c.value(row))}</td>`).join("")}</tr>`).join("");
  const html = `<!doctype html><html><head><meta charset="utf-8"><style>
  body{font-family:Arial,sans-serif;color:#111827}.title{font-size:20px;font-weight:700}.meta{font-size:12px;color:#475569;margin:3px 0}
  table{border-collapse:collapse;width:100%;margin-top:16px}th,td{border:1px solid #cbd5e1;padding:7px;font-size:12px}th{background:#eef2ff;text-align:left}
  </style></head><body><div class="title">${esc(title)}</div>${meta.map((m)=>`<div class="meta">${esc(m)}</div>`).join("")}<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></body></html>`;
  const blob = new Blob(["\ufeff", html], { type: "application/vnd.ms-excel;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".xls") ? filename : `${filename}.xls`;
  a.click();
  URL.revokeObjectURL(url);
}

export function printReport(title: string, meta: string[], logoUrl: string | null | undefined, summaryHtml: string, tableHtml: string) {
  const win = window.open("", "_blank", "noopener,noreferrer,width=1100,height=800");
  if (!win) return false;
  win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(title)}</title><style>
    @page{size:A4;margin:13mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#0f172a;margin:0}.head{display:flex;gap:14px;align-items:center;border-bottom:2px solid #e2e8f0;padding-bottom:12px;margin-bottom:18px}.logo{width:54px;height:54px;object-fit:contain;border-radius:12px}.title{font-size:22px;font-weight:800}.meta{font-size:11px;color:#64748b;margin-top:3px}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:14px 0}.card{border:1px solid #dbeafe;border-radius:10px;padding:10px;background:#f8fafc}.card b{font-size:15px;display:block;margin-top:4px}.card span{font-size:10px;color:#64748b}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #cbd5e1;padding:6px;font-size:10px;text-align:left}th{background:#eef2ff}.profit{margin-top:12px;border-radius:10px;padding:12px;background:#ecfdf5;font-weight:800}.loss{background:#fff1f2}.footer{margin-top:18px;font-size:9px;color:#94a3b8;text-align:right}@media print{button{display:none}}
  </style></head><body><div class="head">${logoUrl ? `<img class="logo" src="${esc(logoUrl)}"/>` : ""}<div><div class="title">${esc(title)}</div>${meta.map((m)=>`<div class="meta">${esc(m)}</div>`).join("")}</div></div>${summaryHtml}${tableHtml}<div class="footer">Generated by LondriOne reporting engine</div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);
  win.document.close();
  return true;
}
