"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase-browser";
import { rupiah } from "@/lib/ui";
import { MinusCircle, Plus, ShoppingBag } from "lucide-react";
type Item={service_id:string;quantity:string;unit_price:string;notes:string};
const blankItem:Item={service_id:"",quantity:"1",unit_price:"0",notes:""};
export default function NewOrderPage(){const supabase=createClient();const router=useRouter();const[tenantId,setTenantId]=useState(""),[branches,setBranches]=useState<any[]>([]),[customers,setCustomers]=useState<any[]>([]),[services,setServices]=useState<any[]>([]),[prices,setPrices]=useState<any[]>([]),[branchId,setBranchId]=useState(""),[customerId,setCustomerId]=useState(""),[orderType,setOrderType]=useState("walk_in"),[promisedAt,setPromisedAt]=useState(""),[items,setItems]=useState<Item[]>([{...blankItem}]),[discount,setDiscount]=useState("0"),[serviceFee,setServiceFee]=useState("0"),[deliveryFee,setDeliveryFee]=useState("0"),[notes,setNotes]=useState(""),[error,setError]=useState(""),[saving,setSaving]=useState(false);
async function load(){const{data:{user}}=await supabase.auth.getUser();if(!user)return;const{data:m}=await supabase.from("tenant_memberships").select("tenant_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();if(!m)return;setTenantId(m.tenant_id);const[{data:b},{data:c},{data:s}]=await Promise.all([supabase.from("branches").select("id,name,is_main").eq("tenant_id",m.tenant_id).eq("is_active",true).order("is_main",{ascending:false}),supabase.from("customers").select("id,full_name,phone").eq("tenant_id",m.tenant_id).eq("status","active").is("deleted_at",null).order("full_name"),supabase.from("services").select("id,name,pricing_mode,unit_label,base_price,min_quantity").eq("tenant_id",m.tenant_id).eq("is_active",true).is("deleted_at",null).order("name")]);setBranches(b??[]);setCustomers(c??[]);setServices(s??[]);if(b?.[0])setBranchId(b[0].id)}
useEffect(()=>{load()},[]);useEffect(()=>{(async()=>{if(!branchId||!tenantId)return;const{data}=await supabase.from("branch_service_prices").select("service_id,price").eq("tenant_id",tenantId).eq("branch_id",branchId).eq("is_active",true);setPrices(data??[])})()},[branchId,tenantId]);
function priceFor(serviceId:string){const ov=prices.find(x=>x.service_id===serviceId);const s=services.find(x=>x.id===serviceId);return String(ov?.price??s?.base_price??0)}
function updateItem(i:number,patch:Partial<Item>){setItems(v=>v.map((x,idx)=>idx===i?{...x,...patch}:x))}
function chooseService(i:number,id:string){updateItem(i,{service_id:id,unit_price:priceFor(id)});const s=services.find(x=>x.id===id);if(s?.min_quantity&&Number(s.min_quantity)>0)updateItem(i,{service_id:id,unit_price:priceFor(id),quantity:String(s.min_quantity)})}
const subtotal=useMemo(()=>items.reduce((s,i)=>s+Number(i.quantity||0)*Number(i.unit_price||0),0),[items]);const grand=Math.max(0,subtotal-Number(discount||0)+Number(serviceFee||0)+Number(deliveryFee||0));
async function submit(e:FormEvent){e.preventDefault();setError("");if(!branchId||!items.length||items.some(i=>!i.service_id))return setError("Cabang dan semua layanan wajib dipilih.");setSaving(true);const customer=customers.find(c=>c.id===customerId);const{data:o,error:oe}=await supabase.from("orders").insert({tenant_id:tenantId,branch_id:branchId,customer_id:customerId||null,customer_name:customer?.full_name||"Walk-in Customer",customer_phone:customer?.phone||null,order_type:orderType,promised_at:promisedAt?new Date(promisedAt).toISOString():null,discount_amount:Number(discount||0),service_fee:Number(serviceFee||0),delivery_fee:Number(deliveryFee||0),notes}).select("id").single();if(oe||!o){setSaving(false);return setError(oe?.message||"Gagal membuat order")};const payload=items.map(i=>{const s=services.find(x=>x.id===i.service_id);return{tenant_id:tenantId,branch_id:branchId,order_id:o.id,service_id:i.service_id,item_name:s?.name||"Laundry",pricing_mode:s?.pricing_mode||"weight",unit_label:s?.unit_label||"kg",quantity:Number(i.quantity),unit_price:Number(i.unit_price),notes:i.notes||null}});const{error:ie}=await supabase.from("order_items").insert(payload);setSaving(false);if(ie)return setError(ie.message);router.replace(`/orders/${o.id}`);router.refresh()}
return <div className="mx-auto max-w-5xl space-y-6"><div><h1 className="page-title">Order Baru</h1><p className="muted mt-1">Kasir cepat dengan multi-item dan harga per cabang.</p></div><form onSubmit={submit} className="grid gap-5 xl:grid-cols-[1fr_340px]"><div className="space-y-5"><div className="card p-6"><div className="grid gap-4 sm:grid-cols-2"><div><label className="label">Cabang</label><select className="input" value={branchId} onChange={e=>setBranchId(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div><div><label className="label">Pelanggan</label><select className="input" value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Walk-in Customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.full_name}{c.phone?` • ${c.phone}`:""}</option>)}</select></div><div><label className="label">Tipe Order</label><select className="input" value={orderType} onChange={e=>setOrderType(e.target.value)}><option value="walk_in">Walk-in</option><option value="pickup">Pickup</option><option value="delivery">Delivery</option><option value="pickup_delivery">Pickup + Delivery</option></select></div><div><label className="label">Estimasi Selesai</label><input className="input" type="datetime-local" value={promisedAt} onChange={e=>setPromisedAt(e.target.value)}/></div></div></div>
<div className="card p-6"><div className="mb-4 flex items-center justify-between"><div><h2 className="section-title">Item Laundry</h2><p className="muted">Bisa lebih dari satu layanan dalam satu order.</p></div><button type="button" onClick={()=>setItems([...items,{...blankItem}])} className="btn-secondary gap-2"><Plus size={15}/> Item</button></div><div className="space-y-3">{items.map((it,i)=>{const s=services.find(x=>x.id===it.service_id);return <div key={i} className="rounded-2xl border border-slate-100 bg-slate-50/70 p-4"><div className="grid gap-3 sm:grid-cols-[1fr_120px_150px_44px]"><select className="input" value={it.service_id} onChange={e=>chooseService(i,e.target.value)} required><option value="">Pilih layanan</option>{services.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div><input className="input" type="number" step="0.1" min="0.1" value={it.quantity} onChange={e=>updateItem(i,{quantity:e.target.value})}/><div className="mt-1 text-center text-[10px] text-slate-400">{s?.unit_label||"qty"}</div></div><input className="input" type="number" min="0" value={it.unit_price} onChange={e=>updateItem(i,{unit_price:e.target.value})}/><button type="button" disabled={items.length===1} onClick={()=>setItems(items.filter((_,idx)=>idx!==i))} className="grid h-11 w-11 place-items-center rounded-xl bg-rose-50 text-rose-600 disabled:opacity-30"><MinusCircle size={18}/></button></div><input className="input mt-3" placeholder="Catatan item: noda, warna, jumlah pakaian..." value={it.notes} onChange={e=>updateItem(i,{notes:e.target.value})}/><div className="mt-2 text-right text-sm font-bold">{rupiah(Number(it.quantity||0)*Number(it.unit_price||0))}</div></div>})}</div></div>
<div className="card p-6"><label className="label">Catatan Order</label><textarea className="input min-h-24" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Catatan khusus pelanggan/order..."/></div></div>
<div className="space-y-5"><div className="card sticky top-20 p-6"><div className="flex items-center gap-2"><ShoppingBag className="text-violet-600"/><h2 className="section-title">Ringkasan</h2></div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Subtotal</span><b>{rupiah(subtotal)}</b></div><div><label className="label">Diskon</label><input className="input text-right" type="number" min="0" value={discount} onChange={e=>setDiscount(e.target.value)}/></div><div><label className="label">Service Fee</label><input className="input text-right" type="number" min="0" value={serviceFee} onChange={e=>setServiceFee(e.target.value)}/></div><div><label className="label">Delivery Fee</label><input className="input text-right" type="number" min="0" value={deliveryFee} onChange={e=>setDeliveryFee(e.target.value)}/></div><div className="border-t pt-4"><div className="text-xs font-bold uppercase tracking-wider text-slate-400">Grand Total</div><div className="mt-1 text-3xl font-black">{rupiah(grand)}</div></div></div>{error&&<div className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-600">{error}</div>}<button className="btn-primary mt-5 w-full" disabled={saving}>{saving?"Menyimpan...":"Buat Order"}</button></div></div></form></div>}
