"use client";
import{FormEvent,useEffect,useState}from"react";
import{createClient}from"@/lib/supabase-browser";
import{rupiah}from"@/lib/ui";
import{Ban,Plus,ReceiptText}from"lucide-react";
export default function ExpensesPage(){const supabase=createClient();const[tenantId,setTenantId]=useState(""),[branchId,setBranchId]=useState(""),[branches,setBranches]=useState<any[]>([]),[rows,setRows]=useState<any[]>([]),[category,setCategory]=useState("Operasional"),[description,setDescription]=useState(""),[amount,setAmount]=useState(""),[method,setMethod]=useState("cash"),[reference,setReference]=useState("");
async function context(){const{data:{user}}=await supabase.auth.getUser();if(!user)return null;const{data:m}=await supabase.from("tenant_memberships").select("tenant_id").eq("user_id",user.id).eq("status","active").limit(1).maybeSingle();return m}
async function load(){const m=await context();if(!m)return;setTenantId(m.tenant_id);const{data:b}=await supabase.from("branches").select("id,name").eq("tenant_id",m.tenant_id).eq("is_active",true);setBranches(b??[]);const bid=branchId||b?.[0]?.id||"";if(!branchId&&bid)setBranchId(bid);if(bid){const{data:r}=await supabase.from("expenses").select("id,expense_date,category,description,amount,payment_method,reference_no,status,created_at").eq("tenant_id",m.tenant_id).eq("branch_id",bid).is("deleted_at",null).order("expense_date",{ascending:false}).limit(100);setRows(r??[])}}
useEffect(()=>{load()},[]);useEffect(()=>{if(branchId)load()},[branchId]);async function add(e:FormEvent){e.preventDefault();await supabase.from("expenses").insert({tenant_id:tenantId,branch_id:branchId,category,description,amount:Number(amount),payment_method:method,reference_no:reference||null});setDescription("");setAmount("");setReference("");load()}async function voidExpense(id:string){await supabase.from("expenses").update({status:"void",voided_at:new Date().toISOString()}).eq("id",id);load()}
const total=rows.filter(r=>r.status==="posted").reduce((s,r)=>s+Number(r.amount||0),0);
return <div className="space-y-6"><div className="flex items-end justify-between gap-3"><div><h1 className="page-title">Pengeluaran</h1><p className="muted mt-1">Kontrol biaya operasional per cabang.</p></div><div className="card-amber px-4 py-3 text-right"><div className="text-xs font-semibold text-amber-600">Total tampil</div><div className="font-black">{rupiah(total)}</div></div></div><div className="grid gap-5 xl:grid-cols-[380px_1fr]"><form onSubmit={add} className="card h-fit p-5"><h2 className="section-title">Catat Pengeluaran</h2><div className="mt-4 space-y-3"><select className="input" value={branchId} onChange={e=>setBranchId(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input className="input" value={category} onChange={e=>setCategory(e.target.value)} placeholder="Kategori"/><input className="input" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Keterangan" required/><input className="input" type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Nominal" required/><select className="input" value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="bank_transfer">Transfer</option><option value="qris">QRIS</option><option value="ewallet">E-Wallet</option><option value="other">Lainnya</option></select><input className="input" value={reference} onChange={e=>setReference(e.target.value)} placeholder="Nomor referensi (opsional)"/><button className="btn-primary w-full gap-2"><Plus size={16}/> Simpan Pengeluaran</button></div></form><div className="card overflow-hidden"><div className="divide-y divide-slate-100">{rows.map(r=><div key={r.id} className={`flex items-center gap-3 p-4 ${r.status==="void"?"opacity-50":""}`}><div className="grid h-10 w-10 place-items-center rounded-xl bg-rose-50 text-rose-600"><ReceiptText size={18}/></div><div className="min-w-0 flex-1"><div className="truncate font-bold">{r.description}</div><div className="text-xs text-slate-500">{r.expense_date} • {r.category} • {r.payment_method}</div></div><div className="text-right"><div className="font-black">{rupiah(r.amount)}</div><span className={r.status==="posted"?"badge-success":"badge-neutral"}>{r.status}</span></div>{r.status==="posted"&&<button onClick={()=>voidExpense(r.id)} className="rounded-lg p-2 text-rose-600 hover:bg-rose-50" title="Void"><Ban size={17}/></button>}</div>)}{!rows.length&&<div className="p-10 text-center text-sm text-slate-400">Belum ada pengeluaran.</div>}</div></div></div></div>}
